export const ADDRESSBOOK_FETCH_REQUEST = "ADDRESSBOOK_FETCH_REQUEST";
export const ADDRESSBOOK_FETCH_SUCCESS = "ADDRESSBOOK_FETCH_SUCCESS";
export const ADDRESSBOOK_FETCH_ERROR = "ADDRESSBOOK_FETCH_ERROR";

export const ADDRESSBOOK_CREATE_REQUEST = "CREATE_ADDRESS_REQUEST";
export const ADDRESSBOOK_CREATE_SUCCESS = "CREATE_ADDRESS_SUCCESS";
export const ADDRESSBOOK_CREATE_FAILURE = "CREATE_ADDRESS_FAILURE";

export const ADDRESS_FETCH_REQUEST = "ADDRESS_FETCH_REQUEST";
export const ADDRESS_FETCH_SUCCESS = "ADDRESS_FETCH_SUCCESS";
export const ADDRESS_FETCH_ERROR = "ADDRESS_FETCH_ERROR";
